services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    build:
      context: "./api"
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      - ./api/src:/app/src
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    links:
      - postgres
  web:
    build:
      context: "./web"
      dockerfile: Dockerfile.dev
    volumes:
      - ./web/public:/app/public
      - ./web/src:/app/src
      # - /app/node_modules
    ports:
      - "3000:3000"
