FROM node:18-alpine As development

EXPOSE 3000
COPY ["./package.json", "./package-lock.json", ".eslintrc.js", "tsconfig.json", "tsconfig.build.json", ".env.development", "/app/"]
WORKDIR /app
RUN npm i --quiet

VOLUME /app

CMD npm run start:dev